// A broad list of U.S. colleges and universities for the onboarding school
// autocomplete. Not exhaustive — students can still type a school that isn't
// listed. Covers flagships, major privates, every NESCAC and Ivy, HBCUs,
// military academies, art and music schools, religious institutions, and
// well-known regionals and community colleges across all 50 states.
window.SCHOOLS = [
  // Ivy League
  "Harvard University", "Yale University", "Princeton University", "Columbia University",
  "University of Pennsylvania", "Brown University", "Dartmouth College", "Cornell University",

  // Top research universities (non-Ivy)
  "Stanford University", "Massachusetts Institute of Technology", "California Institute of Technology",
  "University of Chicago", "Northwestern University", "Johns Hopkins University", "Duke University",
  "Vanderbilt University", "Rice University", "Washington University in St. Louis", "Emory University",
  "Carnegie Mellon University", "University of Notre Dame", "Georgetown University",
  "New York University", "University of Southern California", "Tufts University", "Brandeis University",
  "Wake Forest University", "Case Western Reserve University", "Lehigh University",
  "Tulane University", "Boston University", "Boston College", "Northeastern University",
  "George Washington University", "American University", "Howard University",
  "Syracuse University", "Fordham University", "Villanova University", "Pepperdine University",
  "Southern Methodist University", "Texas Christian University", "Baylor University",
  "Brigham Young University", "Marquette University", "Drexel University",

  // NESCAC (small liberal arts athletic conference)
  "Amherst College", "Bates College", "Bowdoin College", "Colby College", "Connecticut College",
  "Hamilton College", "Middlebury College", "Trinity College", "Tufts University",
  "Wesleyan University", "Williams College",

  // Other small liberal arts colleges
  "Swarthmore College", "Pomona College", "Wellesley College", "Carleton College",
  "Claremont McKenna College", "Harvey Mudd College", "Pitzer College", "Scripps College",
  "Davidson College", "Colgate University", "Vassar College", "Grinnell College",
  "Oberlin College", "Kenyon College", "Macalester College", "Barnard College",
  "Smith College", "Mount Holyoke College", "Bryn Mawr College", "Reed College",
  "Occidental College", "Whitman College", "Bard College", "Sarah Lawrence College",
  "Skidmore College", "Hampshire College", "Bennington College", "Marlboro College",
  "College of the Holy Cross", "Bucknell University", "Lafayette College", "Dickinson College",
  "Franklin & Marshall College", "Gettysburg College", "Muhlenberg College", "Ursinus College",
  "Haverford College", "Trinity University", "Sewanee: The University of the South",
  "Wabash College", "DePauw University", "Centre College", "Rhodes College",
  "Allegheny College", "College of Wooster", "Denison University", "Earlham College",
  "Knox College", "Lake Forest College", "Lawrence University", "St. Olaf College",
  "Gustavus Adolphus College", "Hope College", "Kalamazoo College", "Albion College",
  "Beloit College", "Ripon College", "Coe College", "Cornell College",
  "Luther College", "Drake University", "Saint Mary's College of California",
  "Pitzer College", "St. John's College", "Hendrix College", "Berea College",

  // HBCUs (Historically Black Colleges and Universities)
  "Howard University", "Spelman College", "Morehouse College", "Hampton University",
  "Florida A&M University", "North Carolina A&T State University", "Xavier University of Louisiana",
  "Tuskegee University", "Tennessee State University", "Jackson State University",
  "Alabama A&M University", "Alabama State University", "Albany State University",
  "Bowie State University", "Cheyney University of Pennsylvania", "Claflin University",
  "Clark Atlanta University", "Coppin State University", "Delaware State University",
  "Dillard University", "Elizabeth City State University", "Fayetteville State University",
  "Fisk University", "Grambling State University", "Huston-Tillotson University",
  "Johnson C. Smith University", "Kentucky State University", "Lane College",
  "Langston University", "LeMoyne-Owen College", "Lincoln University (PA)",
  "Lincoln University (MO)", "Livingstone College", "University of Maryland Eastern Shore",
  "Meharry Medical College", "Miles College", "Mississippi Valley State University",
  "Morgan State University", "Norfolk State University", "North Carolina Central University",
  "Paine College", "Philander Smith University", "Prairie View A&M University",
  "Saint Augustine's University", "Savannah State University", "Shaw University",
  "South Carolina State University", "Southern University and A&M College",
  "Stillman College", "Talladega College", "Texas Southern University",
  "Tougaloo College", "University of Arkansas at Pine Bluff",
  "University of the District of Columbia", "Virginia State University",
  "Virginia Union University", "Voorhees University", "West Virginia State University",
  "Wilberforce University", "Wiley College", "Winston-Salem State University",
  "Bennett College", "Edward Waters University",

  // Hispanic-Serving Institutions and notable Latino-serving schools
  "Florida International University", "University of Texas Rio Grande Valley",
  "University of Texas at El Paso", "New Mexico State University",
  "California State University, Los Angeles", "California State University, Long Beach",
  "California State University, Fullerton", "University of Houston",
  "Texas State University", "University of New Mexico", "Florida Atlantic University",

  // Military service academies
  "United States Military Academy", "United States Naval Academy",
  "United States Air Force Academy", "United States Coast Guard Academy",
  "United States Merchant Marine Academy", "Virginia Military Institute",
  "The Citadel", "Norwich University", "Texas A&M (Corps of Cadets)",

  // State flagships and major public universities — all 50 states
  "University of Alabama", "Auburn University", "University of Alabama at Birmingham",
  "University of Alaska Anchorage", "University of Alaska Fairbanks",
  "University of Arizona", "Arizona State University", "Northern Arizona University",
  "University of Arkansas", "Arkansas State University",
  "University of California, Berkeley", "University of California, Los Angeles",
  "University of California, San Diego", "University of California, Davis",
  "University of California, Irvine", "University of California, Santa Barbara",
  "University of California, Santa Cruz", "University of California, Riverside",
  "University of California, Merced", "San Diego State University", "San Francisco State University",
  "San Jose State University", "California Polytechnic State University, San Luis Obispo",
  "California State Polytechnic University, Pomona", "California State University, Fresno",
  "California State University, Sacramento", "California State University, Northridge",
  "Sonoma State University", "Humboldt State University", "Chico State University",
  "University of Colorado Boulder", "University of Colorado Denver",
  "Colorado State University", "University of Northern Colorado", "Colorado School of Mines",
  "University of Connecticut", "Central Connecticut State University",
  "Eastern Connecticut State University", "Southern Connecticut State University",
  "Western Connecticut State University",
  "University of Delaware",
  "University of Florida", "Florida State University", "University of Central Florida",
  "University of Miami", "University of South Florida", "Florida Gulf Coast University",
  "University of North Florida", "Florida Atlantic University",
  "University of Georgia", "Georgia Institute of Technology", "Georgia State University",
  "Kennesaw State University", "Georgia Southern University",
  "University of Hawaii at Manoa", "University of Hawaii at Hilo",
  "University of Idaho", "Boise State University", "Idaho State University",
  "University of Illinois Urbana-Champaign", "University of Illinois Chicago",
  "Illinois State University", "Northern Illinois University", "Southern Illinois University Carbondale",
  "DePaul University", "Loyola University Chicago", "Illinois Institute of Technology",
  "Indiana University Bloomington", "Indiana University–Purdue University Indianapolis",
  "Purdue University", "Ball State University", "Butler University",
  "University of Iowa", "Iowa State University", "University of Northern Iowa",
  "University of Kansas", "Kansas State University", "Wichita State University",
  "University of Kentucky", "University of Louisville", "Western Kentucky University",
  "Louisiana State University", "University of Louisiana at Lafayette",
  "Louisiana Tech University", "Loyola University New Orleans",
  "University of Maine", "University of Southern Maine",
  "University of Maryland", "University of Maryland, Baltimore County", "Towson University",
  "Salisbury University", "Loyola University Maryland",
  "University of Massachusetts Amherst", "University of Massachusetts Boston",
  "University of Massachusetts Lowell", "University of Massachusetts Dartmouth",
  "Northeastern University", "Suffolk University", "Bentley University", "Babson College",
  "University of Michigan", "Michigan State University", "Wayne State University",
  "Western Michigan University", "Eastern Michigan University", "Central Michigan University",
  "Oakland University", "Grand Valley State University",
  "University of Minnesota", "University of Minnesota Duluth", "Minnesota State University, Mankato",
  "University of Mississippi", "Mississippi State University", "University of Southern Mississippi",
  "University of Missouri", "University of Missouri-Kansas City", "Missouri State University",
  "Saint Louis University",
  "University of Montana", "Montana State University",
  "University of Nebraska-Lincoln", "University of Nebraska Omaha", "Creighton University",
  "University of Nevada, Las Vegas", "University of Nevada, Reno",
  "University of New Hampshire", "Dartmouth College",
  "Rutgers University", "Rutgers University–Newark", "Rutgers University–Camden",
  "The College of New Jersey", "Rowan University", "Montclair State University",
  "Stevens Institute of Technology", "Princeton University", "Seton Hall University",
  "University of New Mexico", "New Mexico State University",
  "Columbia University", "Cornell University", "Syracuse University", "New York University",
  "Fordham University", "Pace University", "The New School", "Pratt Institute",
  "Parsons School of Design", "Cooper Union", "Yeshiva University", "Hofstra University",
  "Adelphi University", "St. John's University", "Manhattan College",
  "University at Buffalo", "Stony Brook University", "Binghamton University",
  "University at Albany", "Rochester Institute of Technology", "University of Rochester",
  "Rensselaer Polytechnic Institute", "City College of New York", "Hunter College",
  "Brooklyn College", "Queens College", "Baruch College", "John Jay College of Criminal Justice",
  "University of North Carolina at Chapel Hill", "North Carolina State University",
  "University of North Carolina at Charlotte", "University of North Carolina at Greensboro",
  "East Carolina University", "Appalachian State University", "Elon University",
  "High Point University", "Wake Forest University",
  "University of North Dakota", "North Dakota State University",
  "Ohio State University", "University of Cincinnati", "Miami University",
  "Kent State University", "Ohio University", "Bowling Green State University",
  "Cleveland State University", "Wright State University",
  "University of Oklahoma", "Oklahoma State University", "University of Tulsa",
  "Oklahoma City University",
  "University of Oregon", "Oregon State University", "Portland State University",
  "Lewis & Clark College", "Reed College", "Willamette University",
  "Pennsylvania State University", "University of Pittsburgh", "Temple University",
  "Drexel University", "Carnegie Mellon University", "Duquesne University",
  "Saint Joseph's University", "La Salle University", "Bucknell University",
  "University of Rhode Island", "Roger Williams University", "Providence College",
  "University of South Carolina", "Clemson University", "College of Charleston",
  "Coastal Carolina University",
  "University of South Dakota", "South Dakota State University",
  "University of Tennessee", "University of Memphis", "Vanderbilt University",
  "Belmont University", "East Tennessee State University",
  "University of Texas at Austin", "Texas A&M University", "University of Texas at Dallas",
  "Texas Tech University", "University of Houston", "University of North Texas",
  "Sam Houston State University", "Stephen F. Austin State University",
  "Texas State University", "University of Texas at San Antonio",
  "University of Utah", "Utah State University", "Brigham Young University",
  "Weber State University", "Utah Valley University",
  "University of Vermont", "Saint Michael's College", "Champlain College",
  "University of Virginia", "Virginia Tech", "George Mason University",
  "James Madison University", "College of William & Mary", "Old Dominion University",
  "Virginia Commonwealth University", "Liberty University", "Christopher Newport University",
  "University of Richmond",
  "University of Washington", "Washington State University", "Western Washington University",
  "Seattle University", "Gonzaga University", "Whitworth University",
  "West Virginia University", "Marshall University",
  "University of Wisconsin-Madison", "University of Wisconsin-Milwaukee",
  "University of Wisconsin-Eau Claire", "Marquette University",
  "University of Wyoming",

  // Top community colleges and two-year schools
  "Borough of Manhattan Community College", "Pasadena City College", "Santa Monica College",
  "Miami Dade College", "Northern Virginia Community College", "Houston Community College",
  "De Anza College", "Foothill College", "Diablo Valley College", "Orange Coast College",
  "Valencia College", "St. Petersburg College", "Tallahassee Community College",
  "Bunker Hill Community College", "Massachusetts Bay Community College",
  "LaGuardia Community College", "Bronx Community College", "Queensborough Community College",
  "Borough of Manhattan Community College", "City College of San Francisco",
  "Lone Star College", "Austin Community College",

  // Art, design, music, and conservatory schools
  "Rhode Island School of Design", "Pratt Institute", "Parsons School of Design",
  "School of the Art Institute of Chicago", "Maryland Institute College of Art",
  "California Institute of the Arts", "ArtCenter College of Design", "Otis College of Art and Design",
  "Savannah College of Art and Design", "Ringling College of Art and Design",
  "Massachusetts College of Art and Design", "School of Visual Arts", "Cooper Union",
  "Berklee College of Music", "Juilliard School", "New England Conservatory",
  "Manhattan School of Music", "Curtis Institute of Music", "Eastman School of Music",
  "Mannes School of Music", "Cleveland Institute of Music", "Oberlin Conservatory",
  "Tisch School of the Arts", "Yale School of Drama", "Carnegie Mellon School of Drama",
  "American Musical and Dramatic Academy", "Boston Conservatory at Berklee",

  // Other commonly attended schools
  "Worcester Polytechnic Institute", "Rensselaer Polytechnic Institute",
  "Santa Clara University", "Loyola Marymount University", "University of San Diego",
  "University of San Francisco", "University of the Pacific", "Mills College at Northeastern",
  "University of Portland", "Seattle Pacific University",
  "University of Denver", "Colorado College",
  "Quinnipiac University", "Bryant University", "Sacred Heart University", "Fairfield University",
  "Pace University", "Marist College", "Manhattanville College",
  "Loyola University Chicago", "DePaul University", "Saint Xavier University",
  "Xavier University", "University of Dayton", "John Carroll University",
  "Hofstra University", "Stonehill College", "Endicott College", "Bryant University",
  "Wentworth Institute of Technology", "Olin College of Engineering",
  "Cooper Union", "SUNY Polytechnic Institute", "Embry-Riddle Aeronautical University",
  "Florida Institute of Technology", "Stevens Institute of Technology",
  "New Jersey Institute of Technology", "Colorado School of Mines",
  "South Dakota School of Mines and Technology", "Missouri University of Science and Technology",
  "Rose-Hulman Institute of Technology", "Milwaukee School of Engineering",
];
